### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by furroy** [dweremeichik/godot_autopoly_plugin#3]
Nevermind, I am an idiot. I didn't realize when I went to install this from the Asset Library I actually got a different repo.

**Comment by dweremeichik** [comment]
No worries! Make sure you have the latest version (from the 13th) that version prevents extra vertices from being added outside the polygon. 

Do circle back if you have ideas for improvements or run into any oddities.

**Comment by furroy** [comment]
Well tbh I couldn't find your plugin in the AssetLib, I grabbed this one mistaking it for yours: https://gitlab.com/godot_tools/polygon2d_generator
